# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
after_success:
  - Rscript -e 'rmarkdown::render("README.Rmd")'
  - Rscript -e 'pkgdown::build_site(examples = FALSE)'
  - Rscript -e 'covr::codecov()'
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
