language: r
sudo: false
cache: packages
before_install:
- sudo apt-get update
- sudo apt-get install -y libharfbuzz-dev
- sudo apt-get install -y libfribidi-dev
after_success:
- Rscript -e 'rmarkdown::render("README.Rmd")'
- Rscript -e 'pkgdown::build_site()'
- Rscript -e 'covr::codecov()'
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: "$GITHUB_TOKEN"
  keep_history: false
  on:
    branch: master
notifications:
  slack:
    secure: KsItKSNrWzilCje51ahcFYRa62FmzQ8Pl427ymFZohUBoGPeAW/B0guLNLLkJimbQLmUcFa47ZBkX7HOiK8CGmaAKE8/ifmGNPWpjKO9N0r7UuonJ+J1nLxtOAha5KEpgcXoFJDOn6rEfhvDFatVEP5tA6elWTSvDsWvKjcvik5wLwco+rL8drrdh/4YYreB1FhVKElBQQ29HsJjvu+nFZ83YgcF7cZZ4s0HT3yOLZ04a4jTflgHOxb3pBTIz6IbFUzPiw6amxBkE9+oHdt0448/1fpnAHxYsRoUG+BVXWh5iq+X+hWsgJJ48kW5FjAnfv7GttuBQ/+mBzNLJwbyqblKPo1CjMb4q6UV9Z8XXtlDC8c25Sp4iDHVU2aZBPGTK6TiKflOknj0iG1+YOhJCag1d0UsyzQ/ITE3lbbNf1AfgP+h/eGMeFKOiCa9ptgej2ZIu3iR+HVhEMEyemg3cF3mEnu4OHdgP2Vwk3HngFb7JbLbPAa0S1qwQJ4/XI1cjB4R4u1YVXNQ8z/751XuPOqQCFQ/yUEMi6xzD6I8MH7CLcIyE6vWavOKJI/e0jeIxMHiuNkDNWeCOOjy2z9Loeh+55/TURzhTeMcAzaYYqUwJ1c9AWBZH9jbe7k36uvzDfeElXtpIvu0IzJvXwTYh9ZcdE3DiLjX3DzLNQHbrAc=
