---
title: "Surrounding Workflow and Hints&Tips"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Surrounding Workflow and Tips}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# First steps

Do you need question-metadata from Zofar or not?

## Need Metadata from Zofar

### Request Metadata from Zofar

As soon as you start working on a data preparation project for which the data was generated using Zofar, contact the Zofar team by creating a [new issue](https://github.com/dzhw/zofar/issues/new) and ask for question metadata. 
Keep in mind that Zofar works in sprints and which means that if you miss to write down the issue before their planning meeting, they will consider it at the sprint afterwards at the earliest (possibly later due to other issues their product owner considers to be higher).

You will want to use the metadata in the pages-directory, as this corresponds to our model of a question. They will nevertheless also ship a pages directory, which contains questions that are built up from multiple parts (e.g. a single choice item and a free form answer) that are split up into their individual parts.

The Zofar team needs to know the following (example in brackets):

- `dataAcquisitionProjectId`	(nac2018)
- `studyId`	(stu-nac2018)
- `instrumentIds`	(ins1 (ins-nac2018-ins1))
- `dataSetIds`	(ds1 (dat-nac2018-ds1))

### Check jsons and images

After they send you the metadata, you need to have a look at the following variables inside the question jsons and have a look at the question images. If there's something wrong, you can decide whether to just edit it or (better) provide feedback to Zofar so that it does not happen in future metadata deliveries again.

The following variables deserve special attention:

- conceptIds,
- InstrumentNumbers/InstrumentIds
- SurveryNumbers/SurveyIds
- Question_number 

- You need to check whether everything that was multilingual is present in all languages that were shown to the respondent.
- Check that all mandatory fields are filled in. (See the other [vignette](https://dzhw.github.io/questionMetadataPreparation/articles/question_metadata_preparation_introduction.html#excel-spreadsheet))

The images need to look like the participants of the study saw the study. 
Images should be available for all languages.
Check that the images fit to the json -- there was a case once where one image was repeatedly present for multiple questions.

While it's not strictly part of the workflow for preparing the question metadata, please check whether the instruments file provided by Zofar looks like the participants saw it. Meaning that buttons, headers and all languages etc are present. 

## Copy files and use questionMetadataPreparation

Copy the files into the project directory on Faust.

Now it's time for a coffee, because now you will use `questionMetadataPreparation`.

You need to run the function `convert_zofar_export_to_handcrafted_questionnaire`. Please refer to the [documentation of the function](https://dzhw.github.io/questionMetadataPreparation/reference/convert_zofar_export_to_handcrafted_questionnaire.html). Afterwards, you need to run the function [`convert_handcrafted_questionnaires_to_mdm_format`](https://dzhw.github.io/questionMetadataPreparation/reference/convert_zofar_export_to_handcrafted_questionnaire.html). The whole R workflow is described in the [vignette "Introduction to preparing question metadata for the MDM"](https://dzhw.github.io/questionMetadataPreparation/articles/question_metadata_preparation_introduction.html).

## I do not have jsons from Zofar

Please refer to the explanation in the [vignette](https://dzhw.github.io/questionMetadataPreparation/articles/question_metadata_preparation_introduction.html#manually-handcrafted-question-metadata). Besides filling out the excel spreadsheet, you  need to provide the question image png files (no other formats are allowed). 

It could make sense to try out whether OCR is helpful in order to avoid typing everything and to just copy and paste. If you want to use OCR, scan the document in a the highest possible resolution without compression. It could be helpful to sharpen the lines or employ other means to increase readability. Try out different OCR tools, as many of them are slightly different and give different results. Adobe Acrobat PRO is a commonly used option. 


## Importing the data in the metadata management system

In order to import question metadata in the mdm, go into the project cockpit and click the upload button in the questions card.

# What do I need to check after importing the metadata in the mdm?

## RDC-researcher

- Can you import the metadata in the mdm? If not understand the error messages and fix what is wrong. If you cannot make sense of it, ask for help. 
- If there are questions which should not be imported in the mdm, check whether these are truly not imported.
- Check the question types.
- Check whether the `conceptIds` are present.

## RDC-student employee

- Click through the mdm to see whether the appropriate images are shown and whether the content is correct (the latter could also be checked in the excel file). Double check with the screenshot document (English and German).
- If there are fields which are not displayed (`additionalQuestionText.de`, `additionalQuestionText.en`), you can check them by clicking on the curly braces button in the mdm. Double check with the excel file `questions-insX.xlsx`.
- If question metadata were not delivered by Zofar, please double check spelling.
- Make sure questions and variables are linked correctly.
- Make sure the order in the MDM is the same as in the questionnaire.

Do *not* edit the jsons that are imported, but edit the *handcrafted* xlx file.


# FAQ/Troubleshooting

## In what order do I need to use the R functions?

As it came up often: You *always* need to transform the handcrafted format to the mdm format. If you get questionMetadata from Zofar, you first need to transform the metadata from the Zofar format to the handcrafted format and then to the mdm format.


## I cannot open an excel file from Zofar

Check that you use utf-8.
Sometimes the chararacters are not escaped properly. 
This needs to be altered on a case to case basis. Look out for special characters (ä,ö,ü,ß, brackets etc).

# Preload variables

As it stands now, we do not edit preload variables.

# Some hints for new R users

- Check if your R version and the libraries are up to date.
- If you use windows, install the [Rtools](https://cran.r-project.org/bin/windows/Rtools/) and check that you use the version that corresponds to your R version.
- Check whether you have the appropriate version or Rtools installed and whether R can find it.
- You could change the working directory using `setwd()`. If you are unsure what your working directory is, use `getwd()`
- However, usually you *don't* want to use `getwd()` but work in a project manner. You'll need the package/library `here`, as this makes the code independent of your computers directory structure. For more details and background, see [here](https://github.com/jennybc/here_here).
- Paths on windows need to be escaped, ie. `\` becomes `\\`. To make it easier, here's an Rscript for that. Simply copy the path to your clipboard (ctrl + c) and then run the function as `pathPrep()`. Source: https://stackoverflow.com/a/8425591]

```{r}
pathPrep <- function(path = "clipboard") {
    y <- if (path == "clipboard") {
        readClipboard()
    } else {
        cat("Please enter the path:\n\n")
        readline()
    }
    x <- chartr("\\", "/", y)
    writeClipboard(x)
    return(x)
}
```
Or you could replace `\` with `/`

# Usefull links, further documentation

- [readthedocs](https://metadatamanagement.readthedocs.io/de/stable/questions.html)
- [Github repository](https://dzhw.github.io/questionMetadataPreparation/index.html) and the - [introduction how to use questionMetadata Preparation](https://dzhw.github.io/questionMetadataPreparation/articles/question_metadata_preparation_introduction.html)
